### ISSUE TITLE
Add a demo link to the readme

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#102]
Ask user for a demo URL and display it in the readme (just below Homepage link)

**Comment by LucasProcopio** [comment]
I would really appreciate to do this as a good first issue, I will try and let you know the results thanks  :)

**Comment by LucasProcopio** [comment]
I have made a PR and all test cases have passed but one

> greenkeeper/verify Expected — Waiting for status to be reported

What should I do about this one ? 😃 

thanks in advance :)  I am enjoying contributing.
