### ISSUE TITLE
Get author Github website page url if exists

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#124]
We can retrieve user infos thanks to Github API

**Comment by anku255** [comment]
@kefranabg  Can I please work on this issue?

**Comment by kefranabg** [comment]
sure.

**Comment by anku255** [comment]
Thanks! I am working on it.

**Comment by anku255** [comment]
Hi @kefranabg! 

I am struggling to understand this issue. It would be a great help if you could elaborate on what you meant by "Author's GitHub Home Page URL". 

Did you mean 'Project Homepage'? If yes then how can we fetch that using Github API?

Thank you.

**Comment by kefranabg** [comment]
If you go to my github user page, you'll find this link `https://www.franck-abgrall.me/`. This is the github user website. I would like to get this link if it exists.
