### ISSUE TITLE
Wrong profile url in .all-contributorsrc file and readme file

### ISSUE THREAD

**Issue by Kushagra-ag** [kefranabg/readme-md-generator#128]
**Describe the bug**
Hey, I think you accidently added a wrong url to my profile in .all-contributorsrc and readme file.
The correct url to my profile will be - https://github.com/Kushagra-ag

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kefranabg** [comment]
Seems all-contributors did wrong ;) Would you mind open a PR to fix this ? README and contributorsrc have to be updated

**Comment by Kushagra-ag** [comment]
Sure. PR #129
