### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by tbetous** [kefranabg/readme-md-generator#135]
**Describe the bug**
After npm i I get :

```
added 848 packages from 518 contributors and audited 866797 packages in 8.136s
found 8483 high severity vulnerabilities
```

**To Reproduce**

1. git clone git@github.com:kefranabg/readme-md-generator.git
2. cd readme-md-generator
3. npm install

**Expected behavior**
Get less vulnerabilities

**Screenshots**

**Desktop (please complete the following information):**

- Node: v10.15.3
- npm: 6.9.0

**Comment by kefranabg** [comment]
Upgrade some dependencies should probably fix this.

**Comment by tbetous** [comment]
I did `npm audit fix`, it solves the problem.
