### ISSUE TITLE
User should be warned a README.md already execute before executing readme-generator

### ISSUE THREAD

**Issue by tbetous** [kefranabg/readme-md-generator#140]
**Is your feature request related to a problem? Please describe.**
User should be warned a README.md already exists before executing readme-generator

**Describe the solution you'd like**
If the user have already a README.md, the first question should warn the user that the generation will erase the existing README.md and ask if he wants to continu.

`readme-generator will erase and replace your current README.md. Are you sure you want to continue? (Y/n)`

**Comment by kefranabg** [comment]
Message should be: `readme-md-generator will overwrite your current README.md. Are you sure you want to continue? (Y/n)`

**Comment by globefire** [comment]
assign this to me please @tbetous @kefranabg

**Comment by kefranabg** [comment]
Hi @globefire, this issue is already assigned to @tbetous

**Comment by arguiot** [comment]
This issue should be closed I guess...
