### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#156]
https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project

https://www.contributor-covenant.org

https://github.com/bpetetot/conference-hall/blob/master/docs/CODE_OF_CONDUCT.md

**Comment by Yexan** [comment]
I'm on it ! 😊

**Comment by Yexan** [comment]
https://github.com/kefranabg/readme-md-generator/pull/157
