### ISSUE TITLE
LICENSE badge not working properly

### ISSUE THREAD

**Issue by vccolombo** [kefranabg/readme-md-generator#164]
Hello!! I may have found a bug, could you take a look at it? Thank you very much!

**Describe the bug**
When I generate a new README, the link to the LICENSE badge seems to be wrong. For example for my note-taking project it's linked to `src="https://img.shields.io/github/license/vccolombo/notes-app"` instead of `src="https://img.shields.io/badge/License-MIT-yellow.svg"` (what was being created some weeks ago).
I took an screenshot for you to see what is appearing in the README: https://imgur.com/a/PW9Y2yh

**To Reproduce**
I only have tested it with MIT license and by overwriting an old README (not previously created by readme-md-generator)

1. Run the readme-md-generator
2. Have the LICENSE set up in readme-md-generator options that show up
3. Bug happens

**Expected behavior**
A few weeks ago the behavior was that the badge had a link for `src="https://img.shields.io/badge/License-MIT-yellow.svg"`. I think this is the expected behavior.

**Screenshots**
what shows up in LICENSE badge: https://imgur.com/a/PW9Y2yh
readme-md-generator command options: https://imgur.com/a/N5PcIrZ
You can also take a look at this branch in one of my repos to see what is being generated in README: https://github.com/vccolombo/note-taking/tree/test-readme-generator

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04

**Comment by kefranabg** [comment]
Hi @vccolombo 

I don't think this is a bug. The repository `vccolombo/notes-app` does not exists on github.
I look into your GH projects and found `vccolombo/note-taking`. I think you just forgot to rename the name property in the package.json, so readme-md-generator suggests you the old name, and you've accepted 😉

I'll close this issue but feel free to comment if that's not ok for you.

**Comment by vccolombo** [comment]
Hey @kefranabg 
You are indeed correct. I managed to do the same mistake in two repositories and I tough it was a bug. Sorry for that.

But still, could you please elaborate how the LICENSE badge is being generated? The only thing was wrong was the "name" in package.json, is it using this property to generate the badge? I though that by having the correct LICENSE link (and the "repository" property, also) it shouldn't be a problem... 

Thank you very much for your time ;)
