### ISSUE TITLE
The "Install command" question has a default value even if I keep it empty

### ISSUE THREAD

**Issue by bpetetot** [kefranabg/readme-md-generator#166]
**Describe the bug**
I'm using readme-md-generator to a project that is not a node projet (no `package.json`)
When it asks the "Install command" question, I keep it empty to skip it as it is written:

But it doesn't skip it. It writes the default value `npm install` instead even if it's not a node project.

**To Reproduce**

1. Create an empty folder
2. Launch `npx readme-md-generator` in it
3. Skip all the questions
4. When skipping the "Install command" question, it writes `npm install`

Here a video:
![render1572545446336](https://user-images.githubusercontent.com/516360/67974895-7b04c880-fc13-11e9-9e3a-a888b584fb02.gif)

**Expected behavior**
When I keep an empty value for the question "Install command", I should skip the section with an empty value.

**Comment by kefranabg** [comment]
Hey @bpetetot,

Thanks for this clean issue report !

When looking at your video, if I correctly understood, I don't think you're really skipping the `install` question  😅You're using the default value `npm install` that readme-md-generator is suggesting. If you want skip it, you need to press delete when you see the default value `npm install`.

But you're right, as no `package-json` was detected, it should suggests an empty value by default. I'll fix this 😉

**Comment by bpetetot** [comment]
I didn't know you could remove the default value by delete button 😅
Indeed an empty value by default for a "not nodejs project" do the trick.
