### ISSUE TITLE
Use npm/yarn

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#167]
If a `package.json` is detected, readme-md-generator should ask to choose between yarn and npm. It would allow suggest install, usage and test command with correct package manager (instead of always using npm)

**Comment by anku255** [comment]
If you want, I can give it a shot.

**Comment by kefranabg** [comment]
Sure, feel free to ask question. I suggest you to use [inquirer list](https://github.com/SBoudrias/Inquirer.js/#prompt-types) to let the user choose between npm and yarn

**Comment by anku255** [comment]
Hi @kefranabg 

This issue can be closed now (#172).

Offtopic:  Hey, can you please tell me about changing the author of a git commit while merging a PR such that it looks like `user1 authored and user2 commited`? And if it is possible to do it on Github itself?

**Comment by kefranabg** [comment]
Hi @anku255 ,

> Offtopic: Hey, can you please tell me about changing the author of a git commit while merging a PR such that it looks like user1 authored and user2 commited? And if it is possible to do it on Github itself?

I don't really understand the question, but I'll try to answer 😉The one who merge will always be marked as commiter, but the author owns the contributions on that PR. Also I don't think you can change that behavior on github. Feel free to discuss here even if the issue is closed

**Comment by anku255** [comment]
Hey!

I recently became the maintainer of `howtographql` repo and whenever I merge a PR, it looks like this - 

<img width="448" alt="Screenshot 2019-12-02 at 4 15 31 PM" src="https://user-images.githubusercontent.com/22813027/70034399-1e604900-15d7-11ea-8194-97509e70d268.png">


But I want it to be like this - 

<img width="461" alt="Screenshot 2019-12-02 at 4 15 48 PM" src="https://user-images.githubusercontent.com/22813027/70034426-2cae6500-15d7-11ea-95fe-c6fba1366cf0.png">

**Comment by kefranabg** [comment]
Oh, this is strange. Actually I don't do anything special to get this format:  `user1 authored and user2 commited` I just use the `squash and merge` button from Github.

**Comment by anku255** [comment]
> Oh, this is strange. Actually I don't do anything special to get this format: `user1 authored and user2 commited` I just use the `squash and merge` button from Github.

Oh, I got it. I guess I need to `sqash and merge` instead of `merge`. I will test it. Thank you 😃
