### ISSUE TITLE
Ask for a link to a contributing guide

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#168]
CLI should ask for a link to a potential contributing guide.

**Comment by anku255** [comment]
I would like to work on this.

**Comment by kefranabg** [comment]
Sure, if the project is a github project, you can suggest the a default value. For example: https://github.com/kefranabg/readme-md-generator/blob/master/CONTRIBUTING.md 

I think the result should be printed as following `You can also take a look at the [contributing guide](link).` after `Feel free to check issues page.`
