### ISSUE TITLE
Running readme-md-generator with -y flag breaks author website

### ISSUE THREAD

**Issue by anku255** [kefranabg/readme-md-generator#180]
**Describe the bug**
Running `readme-md-generator` with `-y` flag outputs incorrect author website. It prints the default function of the `author-website` question instead of its value.

**To Reproduce**
`npx readme-md-generator -y`

**Screenshots**
![image](https://user-images.githubusercontent.com/22813027/68611114-59db8c00-04df-11ea-8c31-6a4e62f53732.png)

**Comment by kefranabg** [comment]
It should execute the function if `default` property is a function in `utils.getDefaultAnswers`. Are you interested in working on this @anku255 ?

**Comment by anku255** [comment]
> It should execute the function if `default` property is a function in `utils.getDefaultAnswers`. Are you interested in working on this @anku255 ?

Yeah, I would love to take a shot at this. 😃
