### ISSUE TITLE
Version number containing dashes break the version badge

### ISSUE THREAD

**Issue by Errorname** [kefranabg/readme-md-generator#189]
**Describe the bug**
If the project has a version number containing dashes, it will break the version badge.

**To Reproduce**

1. `npx readme-md-generator`
2. When asked for a version, enter: "1.0.0-alpha"
3. In the generated readme, find the url of the badge (https://img.shields.io/badge/version-1.0.0--alpha-blue)
4. Observe the error: "404 badge not found"

**Expected behavior**
It should show the correct badge

**Additional context**
On the [shields.io](https://shields.io/) documentation, there is the following part:
```
Using dash "-" separator

https://img.shields.io/badge/<LABEL>-<MESSAGE>-<COLOR>

Dashes --	→	- Dash
Underscores __	→	_ Underscore
_ or Space  	→	  Space
```

Because shields.io uses dashes to separate the variables, if we want a dash in our version number, we actually need to put two dashes.

So, when building a shield badge, we should first replace all dashes with double dashes, all underscors with double underscores, and all spaces with underscores

**Comment by kefranabg** [comment]
Thanks for this clean issue report 🙏 

This kind of bug has been fixed for [the license badge](https://github.com/kefranabg/readme-md-generator/pull/141/files).

I'll do the same for the version ;)

**Comment by kefranabg** [comment]
Will be available in the next release 👌
