### ISSUE TITLE
Option to list down features of Project

### ISSUE THREAD

**Issue by nikhilm19** [kefranabg/readme-md-generator#204]
**Is your feature request related to a problem? Please describe.**
Problem of describing everything about the project in the short description

**Describe the solution you'd like**
An option to list down the features of the Project seperately

**Additional context**
Screenshot of the feature requested here.
<img width="1279" alt="Screenshot 2020-04-12 at 8 13 18 PM" src="https://user-images.githubusercontent.com/22270301/79071675-a16a7c00-7cfa-11ea-9d62-db4d137450d4.png">

**Comment by kefranabg** [comment]
Hey, thanks for submitting an issue. This feature looks very specific to your needs and I think most users won't need it
