### ISSUE TITLE
Doesnt work on golang Project

### ISSUE THREAD

**Issue by MaerF0x0** [kefranabg/readme-md-generator#33]
Doesnt work on my golang proejct. Interested in PRs to extend ?

**Comment by kefranabg** [comment]
For sure 😉 I don't know how it would work with go but feel free to propose an implementation 😄

**Comment by kefranabg** [comment]
Never used go, but I did not found any equivalent of `package.json` for go.`readme-md-generator` is still usable for go lang project, however most of the pre-filled responses will remains empty.

Feel free to re-open this issue if you have any suggestion 👍

**Comment by MaerF0x0** [comment]
The gopkg.toml or whatever go modules uses could be incorporated.
