### ISSUE TITLE
Error on "readme" command : TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by Akecel** [kefranabg/readme-md-generator#37]
When I try to use the "readme" command it returns this error that I may have found in several Issue on other repo but none of the solutions are useful here : 

```
⠋ Gathering project infosreadme [template]

Generate README.md from a template

Positionals:
  template  The name of template you want to use             [défaut: "default"]

Options:
  --version  Affiche le numéro de version                              [booléen]
  --help     Affiche de l'aide                                         [booléen]

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.basename (path.js:1149:5)
    at module.exports (/usr/local/lib/node_modules/readme-md-generator/node_modules/project-name/index.js:8:47)
    at Object.getProjectInfos (/usr/local/lib/node_modules/readme-md-generator/src/project-infos.js:106:16)
    at async mainProcess (/usr/local/lib/node_modules/readme-md-generator/src/cli.js:46:31)
```

Thank you !

**Comment by kefranabg** [comment]
Hi @Akecel , could you provide you OS, node & npm version please ?

**Comment by Akecel** [comment]
For node & Npm the last ones, I think. I installed it later this week on my Mac at work. I could check more precisely on Monday.
And I have MacOs Mojave, I'll give you the exact version on Monday too.

**Comment by kefranabg** [comment]
> this error that I may have found in several Issue on other repo

If I correctly understand, you also get this error from other projects ? Don't you think it's an error related to your specific configuration ?

**Comment by Akecel** [comment]
No, what I meant was that by putting this error on github I found it on other projects (like some projects with react)

**Comment by kefranabg** [comment]
Ok, I'll check that ASAP 😉

**Comment by Akecel** [comment]
Thank you very much! I look forward to trying your tool it looks really good

**Comment by kefranabg** [comment]
Fixed in [last release](https://github.com/kefranabg/readme-md-generator/releases)
