### ISSUE TITLE
Idea: Add note running the generator via `npx`

### ISSUE THREAD

**Issue by bcongdon** [kefranabg/readme-md-generator#51]
A project like this seems like a good candidate for use via [npx](https://www.npmjs.com/package/npx).

It might be worthwhile to note in the "Installation" section of the README that this project can be run with `npx readme-md-generator`. (I've tested this, and it already seems to work)

Thanks for your work on this, it's a great template for making READMEs. 😄👍

**Comment by kefranabg** [comment]
Great idea 😉

**Comment by samit4me** [comment]
Had this exact thought when I used`readme-md-generator` for the first time today. Not sure if anyone was working on updating the README, so I created a PR #55, happy to update if it's not what you were thinking.
