### ISSUE TITLE
Idea: use npm version badge if package exists

### ISSUE THREAD

**Issue by frinyvonnick** [kefranabg/readme-md-generator#54]
You could use `view` command to test if a package exists on `npm`:

`npm view [package]`

If it exists you can use npm version badge instead of generic one. An another improvement would be to let user add a tag to point on a specific version channel. For example `2.0.0-alpha.1`

**Comment by kefranabg** [comment]
Awesome !

Love the idea !

**Comment by engrravijain** [comment]
@frinyvonnick and @kefranabg can I work on this feature?

**Comment by kefranabg** [comment]
@engrravijain Of course 👍

**Comment by engrravijain** [comment]
@kefranabg can you please explain me in more detail, like what exactly is required.

**Comment by kefranabg** [comment]
We want to check if the project is published on npm.

If the project is available on npm, we can use a dynamic version badge ([https://shields.io/category/version](https://shields.io/category/version) => check the npm one) for the README.

If the project is not available on npm, we use a static version badge (this is the current behavior, static version badge is always used)

We can check if a project is available on npm by running : `npm view [package-name]`.
We already know the package name if the user filled the `name` property in his `package.json`

**Comment by kefranabg** [comment]
@engrravijain Do you still plan to work on this issue ?

**Comment by SwapnikKatkoori** [comment]
Is anyone on this @kefranabg ? If not, I could try it.

**Comment by kefranabg** [comment]
It's available for now 😉
