### ISSUE TITLE
Idea: Modify existing README

### ISSUE THREAD

**Issue by Marco-Gautier** [kefranabg/readme-md-generator#61]
hi,

It would be cool to be able to pre-fill the different fields when a README.md already exists. We would be able to modify the readme without making a new one from scratch.

Keep up the great work.

**Comment by kefranabg** [comment]
Hmm yes why not 😉

**Comment by kefranabg** [comment]
I thought about this feature, it's a bit complicated but achievable. The thing is, in the future, you will be able to choose between multiple templates for your readme, and there is the problem. It will add too much complexity to be able parse different templates models and get infos from them. 😞

Please feel free to reopen the issue if you have a solution 👍
