### ISSUE TITLE
Different behavior on GitLab vs GitHub

### ISSUE THREAD

**Issue by apatrascu** [kefranabg/readme-md-generator#62]
Hello, I've tested on GitLab and I saw that they are using a different flavor of Markdown and other rules for embedding HTML. 

The default generated HTML looks like this right now on GitLab:
![Selection_001](https://user-images.githubusercontent.com/1193770/59782497-b6d36d00-92c6-11e9-9472-f24c11148ea5.png)

But if the Markdown is written as:
```html
<div align="center">

# Test
</div>
<p>
  <img src="https://img.shields.io/badge/version-2.0-blue.svg?cacheSeconds=2592000" />
</p>
```
it looks correct: 
![Selection_003](https://user-images.githubusercontent.com/1193770/59782441-9efbe900-92c6-11e9-8f4c-1ef7d1834819.png)

**Comment by kefranabg** [comment]
Thanks for the report !  Is the problem `h1` tag ?

**Comment by apatrascu** [comment]
Yes, if you replace it with `<div>`, followed by an enter, and then the text, it is ok.
