### ISSUE TITLE
Idea: Add an EditorConfig file

### ISSUE THREAD

**Issue by apatrascu** [kefranabg/readme-md-generator#63]
For formatting code there is EditorConfig (https://editorconfig.org/) which is supported in all major IDE's (including the ones from JetBrains) and Visual Studio Code through the means of a plugin (`ext install EditorConfig.EditorConfig`).

The format of the file is straightforward, and can cover all files that are used/will be used. For example, something similar with the following can be used on your code:

```
[*]
charset=utf-8
end_of_line=lf
insert_final_newline=true
indent_style=space
indent_size=2
```

If you think it's a good idea, I can create a PR with this feature.

**Comment by kefranabg** [comment]
Hi @apatrascu, thanks for opening this issue.

Code format is already handled by prettier on this project. A Prettier plugin on your with auto format on save do the job. My question is what is the added value of using  EditorConfig ?

**Comment by apatrascu** [comment]
Oh, did not know about Prettier :)

**Comment by kefranabg** [comment]
No problem 😉
