### ISSUE TITLE
npm WARN

### ISSUE THREAD

**Issue by ElecRex** [kefranabg/readme-md-generator#64]
npm installl 

output is :
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 866857 packages in 14.515s
found 0 vulnerabilities

**Comment by kefranabg** [comment]
You use Windows, so fsevents is simply not available to you. You don't need to worry about that. It's a warning, not a fatal error. Feel free to ignore it.

Feel free to reopen this issue if something is blocking for you.
