### ISSUE TITLE
Lock in question. I can't type anything.

### ISSUE THREAD

**Issue by alanlopes4** [kefranabg/readme-md-generator#66]
When i execute, it's locked in second question "project version (use empty value to skip)".I can not type anything and I have to close the terminal. 

![issueGenerator](https://user-images.githubusercontent.com/10770396/59871387-d7a2cd80-936d-11e9-9ba8-2b5307808ba7.png)

**Comment by jpoissant** [comment]
I have the same issue :(

**Comment by piyush97** [comment]
Same Issue!

**Comment by kefranabg** [comment]
Same issue... Only occurs when downloaded through npm registry 🤔

**Comment by kefranabg** [comment]
Just found that the issue comes from the last version of inquirer (6.4.0) [https://github.com/SBoudrias/Inquirer.js/issues/811](https://github.com/SBoudrias/Inquirer.js/issues/811)

**Comment by kefranabg** [comment]
Fixed in [https://github.com/kefranabg/readme-md-generator/commit/688c754584bfb7d9191eb30e18563e16f2a7b3ff](https://github.com/kefranabg/readme-md-generator/commit/688c754584bfb7d9191eb30e18563e16f2a7b3ff) 🎉
