### ISSUE TITLE
misbehavior on github and bitbucket 

### ISSUE THREAD

**Issue by hangyan** [kefranabg/readme-md-generator#73]
On gitlab:

![image](https://user-images.githubusercontent.com/3939015/59963100-fe553580-9520-11e9-89d1-3362d5970a2e.png)

On bitbucket 

![image](https://user-images.githubusercontent.com/3939015/59963102-07de9d80-9521-11e9-87f2-25752672c67c.png)

same project

**Comment by kefranabg** [comment]
Duplicate of #60
