### ISSUE TITLE
Create a template without HTML tags

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#74]
**The problem:**

Some platforms (like [bitbucket](https://bitbucket.org/tutorials/markdowndemo/src/master/)) does not support HTML tags in markdown. See #60 

**Solution:**
The solution would be to create a second template named `no-html` that generates the same README content as the default one, but without HTML tags.

When you start the command `npx readme-md-generator`, it would display the list of available template, and you would be able to choose the one you want (use [inquirer list](https://github.com/SBoudrias/Inquirer.js#list---type-list) for this feature) : 

Example :

```
npx readme-md-generator
? Choose a template
> default.md (the default readme-md-generator template)
  default-no-html (the default readme-md-generator template without html tags)
```

**Comment by nourkilany** [comment]
If it's possible I wanna give this a try

**Comment by kefranabg** [comment]
Hi @nourkilany,

Thanks for your interest

Unfortunately I'm already assigned to this issue and it's almost done 😉 

Feel free to check other good first issues if you want to contribute.

**Comment by nourkilany** [comment]
I really like this project and the effort you put into it. I'll avidly wait for a good first issue that I can fix.

**Comment by kefranabg** [comment]
Thanks @nourkilany
