### ISSUE TITLE
Command list "&" become "&amp"

### ISSUE THREAD

**Issue by Epistol** [kefranabg/readme-md-generator#87]
Looks like a utf bug, when you setup a new readme, in the "Install command" line, setting something with "&" will result in "&amp" in the final readme.

**Comment by wonism** [comment]
I think you should choose **No** when the CLI ask you to `Use HTML in your README.md for a nicer rendering? (not supported everywhere. ex: Bitbucket)`

**Comment by Epistol** [comment]
It occurs when you choose **No** either :/
