### ISSUE TITLE
Twitter and Github username `@`

### ISSUE THREAD

**Issue by Slashgear** [kefranabg/readme-md-generator#92]
I wanted to generate a readme for one of my project.

When I received this question `🐦  Twitter username (use empty value to skip)`

I instantly wrote `@Slashgear_`, which is my valid twitter username. This URL is totally valid https://twitter.com/@Slashgear_

But it has generate this in the template:

```md
* Twitter: [@@Slashgear_](https://twitter.com/@Slashgear_)
```

**Same problem for Github**

- Should we add help in the question `(without the @ )` ?
- Should we parse it to remove the @ on the fly ?

**Comment by kefranabg** [comment]
Hi @Slashgear,

Thanks for opening an issue 🙏

A valid Twitter username is without the `@` prefix, but I understand that the user can easily do the mistake. For a better user experience, I think we should automatically remove the `@` from  the user input answer for github and Twitter. 

Are you interested in doing à PR ?

**Comment by Slashgear** [comment]
It's seems that there is no *on the fly* transform in the *askQuestion* part. Should I add one ?

**Comment by kefranabg** [comment]
I think you can transform user answer directly in `author-twitter` and `author-github` files with the `transformer` property from [inquirer](https://github.com/SBoudrias/Inquirer.js/)

**Comment by Slashgear** [comment]
Ok, I'm on it ! 💪
